import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from '../components/toastprovider';

export const metadata: Metadata = {
  title: "Rubik's Cube Solver",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastProvider/>
      </body>
    </html>
  );
}