import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from '../components/toastprovider';

import { LoaderProvider } from "../loader/LoaderProvider";

import LayoutWrapper from "../components/LayoutWrapper";


export const metadata: Metadata = {
  title: "Rubik's Cube Solver",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LoaderProvider>
        <ToastProvider/>
       <LayoutWrapper>
        {children}
       </LayoutWrapper>
        <ToastProvider/>
        </LoaderProvider>
      
      </body>
    </html>
  );
}